apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: apps
spec:
  components:
  - name: apps
    type: kustomize
    properties:
      repoType: git
      url: https://github.com/rasouza/rasouza-infra
      # the pull interval time, set to 10m since the infrastructure is steady
      pullInterval: 1m
      git:
        branch: kubevela
      path: ./apps