apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: infra-app
spec:
  components:
  - name: infrastructure
    type: kustomize
    properties:
      repoType: git
      url: https://github.com/rasouza/rasouza-infra
      # the pull interval time, set to 10m since the infrastructure is steady
      pullInterval: 10m
      git:
        branch: kubevela
      path: ./infrastructure