apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: argocd-virtual-svc
  namespace: argocd
spec:
  hosts:
    - argocd.localhost
  gateways:
    - argocd-gateway
  tls:
  - match:
    - port: 443
      sni_hosts:
      - argocd.localhost
    route:
    - destination:
        host: argocd-server
        port:
          number: 443
  http:
  - route:
    - destination:
        host: argocd-server
        port:
          number: 80
---

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: argocd-gateway
  namespace: argocd
  labels:
    release: istio
spec:
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
      - "*"
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: PASSTHROUGH
    hosts:
      - "*"
    # Additional ports in gateaway for the ingressPorts - apps using dedicated port instead of hostname
---