apiVersion: v1
kind: Secret
metadata:
  name:  github-secret
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
data:
   clientSecret: ZGE5NjIyOTY5MTU0ODUxYWFhMjBkZWI4MzI4YjdjMmEyOGUyNzVhZQ==
type: Opaque