apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - catalog_source.yaml
  - operator_group.yaml
  - subscription.yaml
  - prometheus-subscription.yaml
  - namespace.yaml
  - argocd.yaml
  - github-secret.yaml