apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: buildkite
    namespace: argocd
    finalizers:
        - resources-finalizer.argocd.argoproj.io
spec:
    destination:
        name: ""
        namespace: buildkite
        server: https://kubernetes.default.svc
    source:
        path: ""
        repoURL: https://buildkite.github.io/charts/
        targetRevision: 0.5.0
        chart: agent
        helm:
            parameters:
                - name: ENC[AES256_GCM,data:IjUJVuYOtOYO5g==,iv:GJtgIZG9rpcqLQzqOJgzhuYan9mJRgcj2x8bwALwcmU=,tag:8+FLbIIhH7YSzexdcYMYjg==,type:str]
                  value: ENC[AES256_GCM,data:k0/+ddthysnoU2bxHqIVMA2Y5qO8fyAEfxFTjaZq29FW,iv:UC3p3c7i7zXsbvN08X3ygJPqS4USj/ya6wxfNeKhs/s=,tag:Q3IgVad4bHeFqb5FErLnXg==,type:str]
                - name: ENC[AES256_GCM,data:bSjy8EbA5j1vfXY=,iv:IzjIbzXgK8MhvAzFn7OB5d8jf3cEUhDfbR6H/6UoeBA=,tag:EMSHZfNclREZtTfJ9hdqGQ==,type:str]
                  value: ENC[AES256_GCM,data:DgymLgn7WsnVJ4haz4+oAGsVGwcZ1ZizNMQQrDGhDxYRhgTwz0ctgZHi2RP4zPWVv/w=,iv:s/UJsupinR/i3oN+Hjg5iw0ZCmn4+V8W5cTuwwlkGeQ=,tag:NvYCc8XrsHcQPKYh6c6Lmw==,type:str]
                - name: ENC[AES256_GCM,data:pAjdKTcaG6u6ueDEth4TIw==,iv:0mSY0gWfWDM105JuDGauTvpe+Zh3ncR1bGtjx7izYxE=,tag:fhbA2wTntG+Bne1V+Q1OJg==,type:str]
                  value: ENC[AES256_GCM,data:9STw6rAo,iv:emmPQmX9IzY77mLIG4AY5W3AcYcHLgN+Nj9eYMh5qoo=,tag:/BuO+uBhXnUF4Z/DEYYsvQ==,type:str]
                - name: ENC[AES256_GCM,data:NnatJOgMqzTNy0Y7QflZQA==,iv:XGC6qv+Mfnf9K3e0/RsxcoF8ylOM2U+SnP7545TaB0w=,tag:W2QwRhdt0OyZnODAB25rEA==,type:str]
                  value: ENC[AES256_GCM,data:ZyjWwKZvXo7gaGzWx98E5VjR99EjtGU=,iv:4sPALxj4bngSUTwQoMOkq8qehp4OJOLauIJPK1bUcHg=,tag:ISPaG+BNiwVK8cuC/YcYVQ==,type:str]
                - name: ENC[AES256_GCM,data:oW7qMWMiKlhu,iv:7CwZ0EQm4we2hnI5xcF9juz8OdHAjaDKbo74s9fZceE=,tag:alylSMQb+tLwKFTYkEgDlA==,type:str]
                  value: ENC[AES256_GCM,data:n1xg/Hw6,iv:uDf2Sxp84khwjzhRTXWAgphK8fjjm30HuVVayESmixM=,tag:ZBdE5XuZaRLWeCymntSHRw==,type:str]
                - name: ENC[AES256_GCM,data:aRn9EzGv4QF5JrpEiQ==,iv:5lsU+GtFEUZ/uSaml/Ioebpitlee8KT+y0AsVZb9dSo=,tag:ccc0dqTgFAS8F91Oyjnzsg==,type:str]
                  value: ENC[AES256_GCM,data:K++SEtdNoqXraq2MPTr+QGv7UrdifBTMKh2f0AHALJJm5MHBjCVYnTKXZZaDDpSFz9VUsg/cb4N7c99eiieft5X7DXB5j+Z2vSd8RhOA9iQEbVCLOyptAUPw13l8hcN8TOtT50dpLcNLL8VHYoN2DC0fVLAsP8ySYJ/y1JCNiQvVxfHJWJhRneGZgxWqGChB9feFbroNvI50BuV09oUhMRlip40M3ooCX8tojQ1frkUuQgpuao0m/uPP/HeGqkO4obhDADfpuUMlnaw7v2FoKYfvtZEKytOWH4o7a+FKJwkJXxyjIIZ1axoBL683F2zrBxsFWmgmLXU7AI2aLAF1tW4g0cIRPmPyv2ML/fnCsf/PKzKvoaEHRwhhQHGI87ZGZjK0habYmXpysaoG+9IVhzQs/GRBEvh5UlE5NbxipgoYpvhpDEoSEBZrbzyiz5LTBMt3hDXsWh1kpf8zN0yNRFPqnHq3nRGftsDZ7fULdeDxl81N30s1zpQPogIYJ3dRl9T8EepH9UYi2IPRcH2rBSoHtX27tB1PKj+RXLGDSDd9HTR1vME/nLfNdgKiZ0FdhWFwyZ29KrnaP/wSbgwE3qZi+YYa/Xv4GERVqjfw8EP9L2qVcLwoJmtJb5oHGZfL09oBaFVRb/2uIBPSE9AtIjfbFrEfjPB+DtqCC/6didQNeGjRunWJMNI9qBVW4PWob5hAjsG3n1MUj4HHvat1bcu8u1giuMkgOZZOvipzPTajkYqdXcnWYMVB9FpA94Y0dabt1iiTq/gYmhgyg9dlNkqPbILDDJ30gjpJJdDamF43AkTw6doHQXotsKwIljz5dcuBI7UWchQ2iXvih9pBfeMRVVSNLM5+QxuMR1HZbTupdSUeTKrDtFziyxJF863kwD6eDWMA3OvcNQ8dnlp72++XeAOzhGcc66A3eE9bw2rxQIoDnF+SZgWLJYOJFAcyuc0+BiJTe7nK/ezSSxenQcoiggXUyGDoNaG8KKHwIFn67Q+V/1flSAUH5YKbNwYvogRHBqvcTDgIJDGyBEf84jmIfvAKdVKOsWIVXZH1MJ7XGh7x8rjAqX1MgCTVraM1WIy9nGD77nRWB5mdYt5UH6hpF4aXi6Hx1vfzmaXFhTAZv/HHSBD0yTnDx/NHmL+Yu++AYJnjcg2n+8UN70nYBPfZsvtsR2ehEaE5ODPfZZHZMwfSC93p1F8Nou8MiF/20SNgZirJzLuD03IMYktQ5riAoZfSlxgSsQwv1fbar7UlzIvOHrRhGx8UMpDSIdUMqMnchrk8WsOWXw6Qm+8JI/3llbov/FsNnyl/1RzclbB6MNLgx+bOFowCxDSvgV1KEtdDYbPX64otul4aG7vW0PGO0XtwqKV9uYYqh9g/PeUuldyH6TTFNJWTlxVxUaf2GB9VoihuyVLzH5e+rUGJhsks7Rzd5klifoZjHmvRkY26O1lOacDu9eirmzegH0+93BPFDqxFI6Z+EUQ6yZKEuNKdLee9vl5bBzoz3mQCn9/+g7lO+A3aOIANT2NMEZkN34k4HMw8k7cviL/T2t/1gNB3gT01xzUkusO25toxmZkkAdMYiyVGO9bgnfkwqYFAabay1OWW2oF2wH2zAO0/RQVi53b/ny/aVI6k+xlfN3eCjEc58padJgf+T3fwg1pBjmEUlPo83IzGGZZJtF4ieedQkKXn3yw/iqIPOlP+161ikD/CTQcvhhv9vcq/OhDl07UvFgmaHhUsgp89t9g87K7PPwOwIw3ivYuBUIec1EP+cbvVLYSQ960r57U6pCIx7hnI7Sm79u6ufjqcn2z3B1odIDfB1gOxJZDtvz+KfG2HXOincny6Op6NLbdKi5pXoR73di6Mek7JbUquS1JufsQm2uxMX5TvbrroFK79lFbRRajtyhqaUCdqSTGr4eo0Zb5dFuHWxcK4urAIr14VFr5VsanxUNI9FjtXkw9ALzHYwWYRt8Bd0W1LtFXD1mCOAvvBmzlpa+6GYiwur3TiOFGHglR3cLDZ3cOyj9Czj5pmPMqhYrqcnYAWVdA2rrfik6jVVX0nW8WkPA5H+3Vg1z/OGhwXqGR7r3IYl98oq2fwel79fpW3a15JMacy3MxytIn41iGfrstXMyqTzssdDxMr9fAPpLmvpKntsjoIjMHBV0ciMJ9CHUugj5LAh/9jQo5XgkSLP56qQsgZYvvmyG/XQ8Y4wFWWZG/D5XREOUUVz+wejrCol1ohOGRMqHo=,iv:Ue/MpiZo0/lMCkNvka1Xmn6jhZ8M3b1fGMpZTTJBSE4=,tag:pTL9s4AwQHUFsNK5ToB1cA==,type:str]
                - name: ENC[AES256_GCM,data:MHoYupRY69e4qAXfz9QTKDb5tRGTiBB4ELs=,iv:VXizZ1p/dD2/vaElXmq8m7lQEB2akrS5hEA8SvyTrqo=,tag:pdxjQLmqHz54pGAyoEQC8w==,type:str]
                  value: ENC[AES256_GCM,data:Ky9qMnzDxDWUzmPU7As3yovj7uM+r5x/F3Nrntrii4lUebEXTQty1HDElZg1ECccPtsNmieWaRRk1jHAWM6yr+qJmuMfiV4naTaD4qeDviyJnUcH4bzbz9lEUyu1DY1LMd4AkpyDaeEBRwGCSWVaLDmD6ihpMk79/hoI1AUSjLX3JuWvLgaAYA==,iv:kvFYfNCAql78RFQ6fDnRB+47U+qYQJ4o7mwUOws20R0=,tag:eSxrmOSJlkZfDkqKJ2akpQ==,type:str]
    project: default
    syncPolicy:
        automated:
            prune: true
        syncOptions:
            - CreateNamespace=true
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/programming-diary-prod/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2021-01-10T21:54:21Z"
          enc: CiQAFnBk+EdCyhwEshGVyhgqj1ssR37PrrUm230iVn3k663mF9gSSQBlm1NMQmbplXecwz9/q1z+RBQHyqiXb4TjfzJ7ok/dCcPqu3i5Jp119c2NdwGFl2L7JkWgHnBbDV4aoepbYTS+FYvwD7bSrWE=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-18T00:35:56Z"
    mac: ENC[AES256_GCM,data:wiDy/2uYuezUaEG4VC17v7CEKXjV/Lc3JnKeaq3je4MpEdNdemcxck3GVu3jKhYHjndDZ6aqM7SIfgf24unAx0Wif6UnZj4ZpgRFSIf/0hsHaUyfNNIxkIc2+dkXsDOy/zaYabYzAfFNvhIEFTJLMuCqg5kpw8fUbMhB0Kk9KPs=,iv:AZNFycgvtAX4aoAZqIcIQot/XB7YtIl26yntZ0W1BKA=,tag:H6JQLibcR4ZlS3771RC68g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.7.1
