apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ""
    namespace: hashicorp
    server: https://kubernetes.default.svc
  source:
    path: ""
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.4.1
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
