apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ""
    namespace: hashicorp
    server: https://kubernetes.default.svc
  source:
    path: ""
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.19.0
    helm:
      parameters:
        - name: server.affinity
          value: ""
        - name: server.ha.enabled
          value: "true"
        - name: server.ha.replicas
          value: "1"
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
