name: consul
services:
  consul:
    chart: consul
    targetNamespace: hashicorp
    type: helm
    url: https://helm.releases.hashicorp.com
    version: 0.40.0
    values:
      client:
        enabled: true
      server:
        affinity: ""
        replicas: 1
        bootstrapExpect: 1
        disruptionBudget:
          maxUnavailable: 0