apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: consul
spec:
  components:
    - name: consul
      type: helm
      properties:
        chart: consul
        targetNamespace: hashicorp
        version: "*"
        url: https://helm.releases.hashicorp.com
        repoType: helm
        values:
          client:
            enabled: true
          server:
            affinity: ""
            replicas: 1
            bootstrapExpect: 1
            disruptionBudget:
              maxUnavailable: 0