apiVersion: v1
kind: Namespace
metadata:
  name: diary
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: diary-external-secret
  namespace: diary
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: diary-core-secret
  dataFrom:
    - key: diary/database
    - key: diary/token
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: diary-frontend-external-secret
  namespace: diary
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: diary-frontend-secret
  dataFrom:
    - key: diary/auth
