apiVersion: v1
kind: ConfigMap
data:
  config.js: |
    window.FEATURES_ENDPOINT='http://api.feature.k8s.local/api/features/key_dev_b65f7066608d06da'
    window.CORE_URL='https://diary-core.rasouza.dev'
    window.SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImlhdCI6MTYyOTU4MTk0MSwiZXhwIjoxOTQ1MTU3OTQxfQ.dFX_AxjSbjy9o34c-al9msFtJxVtUPmX0ZzW3saxOxc"
    window.SUPABASE_URL="https://cggwvqtadgufjgzxreuq.supabase.co"
metadata:
  name: diary-frontend-configmap
  namespace: diary