apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: external-secrets
spec:
  components:
    - name: external-secrets
      type: helm
      properties:
        chart: kubernetes-external-secrets
        targetNamespace: external-secrets
        version: "*"
        url: https://external-secrets.github.io/kubernetes-external-secrets/
        repoType: helm