apiVersion: v1
kind: Namespace
metadata:
  name: gamepass
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: gamepass-external-secret
  namespace: gamepass
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: gamepass-bot-secret
  dataFrom:
    - key: gamepass/database
    - key: gamepass/logger
    - key: gamepass/discord
