apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: git-external-secret
  namespace: default
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: git-secret
    template:
      type: kubernetes.io/basic-auth
  dataFrom:
    - key: git/auth
