apiVersion: v1
kind: Namespace
metadata:
  name: growthbook
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: growthbook-external-secret
  namespace: growthbook
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: growthbook-secret
  dataFrom:
    - key: growthbook/database
