apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: vault
spec:
  components:
    - name: vault
      type: helm
      properties:
        chart: vault
        targetNamespace: hashicorp
        version: "*"
        url: https://helm.releases.hashicorp.com
        repoType: helm
        values:
          server:
            affinity: ""
            ha:
              enabled: true
              replicas: 1