apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: diary-frontend-app
spec:
  components:
    - name: diary-frontend
      type: webservice
      properties:
        image: rasouza/diary-frontend:5ea6fcb
        port: 80
        volumeMounts:
          configMap:
            - name: frontend-env
              mountPath: /usr/share/nginx/html
              cmName: diary-frontend-configmap
              items:
                - key: config.js
                  path: env/config.js
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d
              cmName: diary-frontend-configmap
              items:
                - key: default.conf
                  path: default.conf
      traits:
        - type: gateway
          properties:
            domain: diary.k8s.rasouza.dev
            http:
              "/": 80
        - type: annotations
          properties:
            "reloader.stakater.com/auto": "true"
  policies:
    - name: multi-env
      type: env-binding
      properties:
        envs:
          - name: local
            placement:
              namespaceSelector:
                name: diary
            patch:
              components:
                - name: diary-frontend
                  traits:
                    - type: gateway
                      properties:
                        domain: diary.k8s.local
