apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: diary-core-app
spec:
  components:
    - name: diary-core
      type: webservice
      properties:
        image: rasouza/diary-core:822d17b
        port: 3001
        env:
          - name: LOG_LEVEL
            value: info
          - name: SENTRY_DSN
            value: https://380cd006121c462cb81993a4f85081ed@o47773.ingest.sentry.io/5585158
          - name: APP_URL
            value: https://diary.rasouza.dev
      traits:
        - type: gateway
          properties:
            domain: diary-core.k8s.rasouza.dev
            http:
              "/": 3001
        - type: service-binding
          properties:
            envMappings:
              JWT_SECRET:
                secret: diary-core-secret
              SUPABASE_KEY:
                secret: diary-core-secret
              SUPABASE_URL:
                secret: diary-core-secret
        - type: annotations
          properties:
            "reloader.stakater.com/auto": "true"
  policies:
    - name: multi-env
      type: env-binding
      properties:
        envs:
          - name: local
            placement:
              namespaceSelector:
                name: diary
            patch:
              components:
                - name: diary-core
                  properties:
                    env:
                      - name: LOG_LEVEL
                        value: debug
                  traits:
                    - type: gateway
                      properties:
                        domain: diary-core.k8s.local
