CREATE DATABASE diary;
CREATE USER diary_idp WITH ENCRYPTED PASSWORD 'secret';
CREATE USER diary_user WITH ENCRYPTED PASSWORD 'secret';

\c diary
CREATE SCHEMA users AUTHORIZATION diary_user;
CREATE SCHEMA idp AUTHORIZATION diary_idp;
