apiVersion: batch/v1
kind: Job
metadata:
  name:  diary-migration-job
  namespace: postgres
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      restartPolicy: OnFailure
      containers:
      - name: diary-migration
        image: docker.io/bitnami/postgresql:11.7.0-debian-10-r77
        command: ["/bin/sh", "-c"]
        args:
        - >
          curl https://raw.githubusercontent.com/rasouza/diary-infra/ansible/postgres/init.sql | PGPASSWORD=postgres psql -h $(POSTGRES_SVC) -U postgres